// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008142329_chay_lan_02")]
    partial class chay_lan_02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà đóng chai"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì ăn liền, phở khô, cháo gói"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, tương ớt, sốt mayonnaise"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Khô & Đồ ăn vặt mặn",
                            Description = "Khô gà, khô bò, mực khô, cá khô"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Hạt & Đồ ăn vặt dinh dưỡng",
                            Description = "Hạt điều, hạnh nhân, đậu phộng, hạt hướng dương"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Đồ ăn vặt cay",
                            Description = "Snack cay, bánh tráng cay, mì cay"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Bánh tráng",
                            Description = "Bánh tráng trộn, bánh tráng cuộn, bánh tráng sa tế"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Đồ ăn vặt ngọt",
                            Description = "Bánh ngọt, kẹo, thạch, socola"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Trái cây sấy",
                            Description = "Xoài sấy, mít sấy, chuối sấy, khoai lang sấy"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Đồ ăn vặt đông lạnh",
                            Description = "Xúc xích, cá viên, bò viên, nem chua"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Cà phê & Thức uống pha sẵn",
                            Description = "Cà phê lon, cà phê hòa tan, cacao"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Kem & Đồ ăn lạnh",
                            Description = "Kem que, kem hộp, pudding, thạch lạnh"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Combo đồ ăn vặt",
                            Description = "Combo snack, combo bánh kẹo, combo ăn vặt"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901234567",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Lê Văn Việt, Phường Hiệp Phú, Thành phố Thủ Đức, TP. Hồ Chí Minh",
                            CustomerName = "Trần Thị Bình",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "78 Cách Mạng Tháng 8, Phường 6, Quận 3, TP. Hồ Chí Minh",
                            CustomerName = "Lê Văn Cường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983456789",
                            RewardPoints = 20
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "12 Phan Xích Long, Phường 2, Quận Phú Nhuận, TP. Hồ Chí Minh",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0904567891",
                            RewardPoints = 200
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "56 Đinh Tiên Hoàng, Phường Đa Kao, Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Hoàng Văn Đức",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0915678902",
                            RewardPoints = 65
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "89 Nguyễn Văn Trỗi, Phường 8, Quận Phú Nhuận, TP. Hồ Chí Minh",
                            CustomerName = "Võ Thị Hà",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0986789013",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "234 Võ Văn Tần, Phường 5, Quận 3, TP. Hồ Chí Minh",
                            CustomerName = "Đặng Minh Hoàng",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0907890124",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "345 Hai Bà Trưng, Phường 8, Quận 3, TP. Hồ Chí Minh",
                            CustomerName = "Bùi Thị Lan",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918901235",
                            RewardPoints = 95
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "67 Lý Tự Trọng, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Đỗ Văn Nam",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0989012346",
                            RewardPoints = 30
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "90 Pasteur, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Thị Mai",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901123456",
                            RewardPoints = 250
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "15 Hoàng Văn Thụ, Phường 15, Quận Phú Nhuận, TP. Hồ Chí Minh",
                            CustomerName = "Trần Văn Phúc",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912234567",
                            RewardPoints = 70
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "228 Cộng Hòa, Phường 12, Quận Tân Bình, TP. Hồ Chí Minh",
                            CustomerName = "Lý Thị Quỳnh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983345678",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "510 Trường Chinh, Phường 13, Quận Tân Bình, TP. Hồ Chí Minh",
                            CustomerName = "Phan Minh Tâm",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0904456789",
                            RewardPoints = 320
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "75 Quang Trung, Phường 10, Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Huỳnh Thị Thảo",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0915567890",
                            RewardPoints = 110
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "302 Nguyễn Oanh, Phường 17, Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Đinh Văn Tuấn",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0986678901",
                            RewardPoints = 40
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "893456789001",
                            CategoryId = 1,
                            Price = 15000m,
                            ProductName = "Snack khoai tây vị phô mai",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "893456789002",
                            CategoryId = 1,
                            Price = 25000m,
                            ProductName = "Bánh quy socola",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "893456789003",
                            CategoryId = 1,
                            Price = 20000m,
                            ProductName = "Kẹo dẻo trái cây",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "893456789004",
                            CategoryId = 2,
                            Price = 12000m,
                            ProductName = "Trà đào đóng chai",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "893456789005",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Nước ngọt Coca Cola",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "893456789006",
                            CategoryId = 3,
                            Price = 15000m,
                            ProductName = "Sữa tươi có đường",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "893456789007",
                            CategoryId = 3,
                            Price = 10000m,
                            ProductName = "Sữa chua vị dâu",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "893456789008",
                            CategoryId = 4,
                            Price = 15000m,
                            ProductName = "Mì cay hải sản",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "893456789009",
                            CategoryId = 4,
                            Price = 12000m,
                            ProductName = "Phở bò ăn liền",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "893456789010",
                            CategoryId = 6,
                            Price = 35000m,
                            ProductName = "Khô gà lá chanh",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "893456789011",
                            CategoryId = 6,
                            Price = 55000m,
                            ProductName = "Khô bò miếng",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "893456789012",
                            CategoryId = 7,
                            Price = 20000m,
                            ProductName = "Hạt hướng dương",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "893456789013",
                            CategoryId = 9,
                            Price = 25000m,
                            ProductName = "Bánh tráng trộn đặc biệt",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "893456789014",
                            CategoryId = 11,
                            Price = 40000m,
                            ProductName = "Xoài sấy dẻo",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "893456789015",
                            CategoryId = 15,
                            Price = 99000m,
                            ProductName = "Combo Ăn Vặt Siêu Cay",
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FunctionScope")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "",
                            FullName = "Nguyễn Quản Trị",
                            FunctionScope = "Toàn quyền toàn bộ hệ thống",
                            IsActive = true,
                            Password = "123456",
                            Role = "Admin",
                            Username = "admin01"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "",
                            FullName = "Trần Giám Đốc",
                            FunctionScope = "Toàn quyền toàn bộ hệ thống",
                            IsActive = true,
                            Password = "123456",
                            Role = "Admin",
                            Username = "admin02"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "",
                            FullName = "Lê Thu Ngân",
                            FunctionScope = "Màn hình POS, Khách hàng thành viên",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier01"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "",
                            FullName = "Phạm Bán Hàng",
                            FunctionScope = "Màn hình POS, Khách hàng thành viên",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier02"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "",
                            FullName = "Hoàng Thu Ngân",
                            FunctionScope = "Màn hình POS, Khách hàng thành viên",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier03"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "",
                            FullName = "Vũ Thị Quầy",
                            FunctionScope = "Màn hình POS, Khách hàng thành viên",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier04"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "",
                            FullName = "Đỗ Bán Lẻ",
                            FunctionScope = "Màn hình POS, Khách hàng thành viên",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier05"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "",
                            FullName = "Ngô Quản Kho",
                            FunctionScope = "Sản phẩm, Nhóm hàng, Nhập xuất kho",
                            IsActive = true,
                            Password = "123456",
                            Role = "Warehouse",
                            Username = "ware01"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "",
                            FullName = "Bùi Kiểm Kê",
                            FunctionScope = "Sản phẩm, Nhóm hàng, Nhập xuất kho",
                            IsActive = true,
                            Password = "123456",
                            Role = "Warehouse",
                            Username = "ware02"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "",
                            FullName = "Dương Thủ Kho",
                            FunctionScope = "Sản phẩm, Nhóm hàng, Nhập xuất kho",
                            IsActive = true,
                            Password = "123456",
                            Role = "Warehouse",
                            Username = "ware03"
                        },
                        new
                        {
                            UserId = 11,
                            Email = "",
                            FullName = "Lý Nhập Hàng",
                            FunctionScope = "Sản phẩm, Nhóm hàng, Nhập xuất kho",
                            IsActive = true,
                            Password = "123456",
                            Role = "Warehouse",
                            Username = "ware04"
                        },
                        new
                        {
                            UserId = 12,
                            Email = "",
                            FullName = "Đặng Hỗ Trợ",
                            FunctionScope = "Toàn quyền toàn bộ hệ thống",
                            IsActive = true,
                            Password = "123456",
                            Role = "Admin",
                            Username = "admin_backup"
                        },
                        new
                        {
                            UserId = 13,
                            Email = "",
                            FullName = "Hồ Ca Chiều",
                            FunctionScope = "Màn hình POS, Khách hàng thành viên",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier06"
                        },
                        new
                        {
                            UserId = 14,
                            Email = "",
                            FullName = "Trương Vận Chuyển",
                            FunctionScope = "Sản phẩm, Nhóm hàng, Nhập xuất kho",
                            IsActive = true,
                            Password = "123456",
                            Role = "Warehouse",
                            Username = "ware05"
                        },
                        new
                        {
                            UserId = 15,
                            Email = "",
                            FullName = "Mai Giám Sát",
                            FunctionScope = "Toàn quyền toàn bộ hệ thống",
                            IsActive = true,
                            Password = "123456",
                            Role = "Admin",
                            Username = "supervisor"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
